const WIPE_DATE = '2026-09-03T20:00:00-04:00';
const toast = document.getElementById('toast');
function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}
document.querySelectorAll('.copy').forEach(btn=>btn.addEventListener('click',async()=>{const ip=btn.dataset.ip;try{await navigator.clipboard.writeText(ip);showToast('SERVER IP COPIED');}catch{showToast(ip)}}));
document.querySelectorAll('.connect').forEach(btn=>btn.addEventListener('click',()=>{const ip=btn.dataset.ip;window.location.href=`steam://connect/${ip}`}));
function updateCountdown(){const end=new Date(WIPE_DATE).getTime(),now=Date.now(),diff=Math.max(0,end-now);const d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);document.getElementById('d').textContent=String(d).padStart(2,'0');document.getElementById('h').textContent=String(h).padStart(2,'0');document.getElementById('m').textContent=String(m).padStart(2,'0');document.getElementById('s').textContent=String(s).padStart(2,'0');document.getElementById('wipeText').textContent=diff?'Next wipe: '+new Date(WIPE_DATE).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'THE WIPE IS LIVE';}updateCountdown();setInterval(updateCountdown,1000);
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
document.querySelector('.menu')?.addEventListener('click',()=>{const nav=document.querySelector('nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='84px';nav.style.left='0';nav.style.right='0';nav.style.padding='25px';nav.style.background='#090909';nav.style.flexDirection='column'});
